# Generated by Django 5.2 on 2026-01-30 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_post_options_post_updated_on_reply_updated_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updated_on',
            new_name='edited_on',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='updated_on',
            new_name='edited_on',
        ),
    ]
