# Generated by Django 5.2 on 2026-01-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_rename_updated_on_post_edited_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='edited_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='edited_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
