# Generated by Django 5.2 on 2026-02-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_garden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='height_cm_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='height_cm_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='is_edible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plant',
            name='spacing_cm',
            field=models.PositiveIntegerField(blank=True, help_text='Recommended plant-to-plant spacing in cm', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='spread_cm_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='spread_cm_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='sun_requirement',
            field=models.CharField(choices=[('full_sun', 'Full sun'), ('part_shade', 'Partial shade'), ('shade', 'Shade'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='plant',
            name='use_type',
            field=models.CharField(choices=[('edible', 'Edible'), ('ornamental', 'Ornamental'), ('both', 'Edible & ornamental'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('vegetable', 'Vegetable'), ('herb', 'Herb'), ('fruit', 'Fruiting plant'), ('fruit_tree', 'Fruit tree'), ('shrub', 'Shrub'), ('ornamental_tree', 'Ornamental tree'), ('flower', 'Flower'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
