# Generated by Django 5.2 on 2026-02-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_garden', '0002_plant_height_cm_max_plant_height_cm_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='height_cm_max',
            field=models.PositiveIntegerField(blank=True, help_text='Optional - typical maximum height in cm', null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='height_cm_min',
            field=models.PositiveIntegerField(blank=True, help_text='Optional - typical minimum height in cm', null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='spread_cm_max',
            field=models.PositiveIntegerField(blank=True, help_text='Optional - typical maximum spread in cm', null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='spread_cm_min',
            field=models.PositiveIntegerField(blank=True, help_text='Optional - typical minimum spread in cm', null=True),
        ),
    ]
