# Generated by Django 5.2 on 2025-08-04 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['plant_name', '-date_planted', 'owner']},
        ),
    ]
